//@HEADER
// ************************************************************************
//
//                        Kokkos v. 4.0
//       Copyright (2022) National Technology & Engineering
//               Solutions of Sandia, LLC (NTESS).
//
// Under the terms of Contract DE-NA0003525 with NTESS,
// the U.S. Government retains certain rights in this software.
//
// Part of Kokkos, under the Apache License v2.0 with LLVM Exceptions.
// See https://kokkos.org/LICENSE for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//@HEADER

#ifndef KOKKOS_CUDA_HALF_MATHEMATICAL_FUNCTIONS_HPP_
#define KOKKOS_CUDA_HALF_MATHEMATICAL_FUNCTIONS_HPP_

#include <Cuda/Kokkos_Cuda_Half_Impl_Type.hpp>
#include <impl/Kokkos_Half_FloatingPointWrapper.hpp>
#include <Kokkos_MathematicalFunctions.hpp>

namespace Kokkos {

#ifdef KOKKOS_HALF_IS_FULL_TYPE_ON_ARCH
#define KOKKOS_CUDA_HALF_UNARY_FUNCTION(OP, CUDA_NAME, HALF_TYPE) \
  KOKKOS_INLINE_FUNCTION HALF_TYPE impl_##OP(HALF_TYPE x) {       \
    return CUDA_NAME(HALF_TYPE::impl_type(x));                    \
  }

#define KOKKOS_CUDA_HALF_BINARY_FUNCTION(OP, CUDA_NAME, HALF_TYPE)       \
  KOKKOS_INLINE_FUNCTION HALF_TYPE impl_##OP(HALF_TYPE x, HALF_TYPE y) { \
    return CUDA_NAME(HALF_TYPE::impl_type(x), HALF_TYPE::impl_type(y));  \
  }

#define KOKKOS_CUDA_HALF_UNARY_PREDICATE(OP, CUDA_NAME, HALF_TYPE) \
  KOKKOS_INLINE_FUNCTION bool impl_##OP(HALF_TYPE x) {             \
    return CUDA_NAME(HALF_TYPE::impl_type(x));                     \
  }

#ifdef KOKKOS_IMPL_CUDA_HALF_TYPE_DEFINED

#define KOKKOS_CUDA_HALF_UNARY_FUNCTION_IMPL(OP, CUDA_NAME) \
  KOKKOS_CUDA_HALF_UNARY_FUNCTION(OP, CUDA_NAME, Kokkos::Experimental::half_t)

#define KOKKOS_CUDA_HALF_BINARY_FUNCTION_IMPL(OP, CUDA_NAME) \
  KOKKOS_CUDA_HALF_BINARY_FUNCTION(OP, CUDA_NAME, Kokkos::Experimental::half_t)

#define KOKKOS_CUDA_HALF_UNARY_PREDICATE_IMPL(OP, CUDA_NAME) \
  KOKKOS_CUDA_HALF_UNARY_PREDICATE(OP, CUDA_NAME, Kokkos::Experimental::half_t)

// Basic operations
KOKKOS_CUDA_HALF_UNARY_FUNCTION_IMPL(abs, __habs)
KOKKOS_CUDA_HALF_UNARY_FUNCTION_IMPL(fabs, __habs)
// KOKKOS_CUDA_HALF_BINARY_FUNCTION_IMPL(fmod)
// KOKKOS_CUDA_HALF_BINARY_FUNCTION_IMPL(remainder)
KOKKOS_CUDA_HALF_BINARY_FUNCTION_IMPL(fmax, __hmax)
KOKKOS_CUDA_HALF_BINARY_FUNCTION_IMPL(fmin, __hmin)
// KOKKOS_CUDA_HALF_BINARY_FUNCTION_IMPL(fdim)
// Exponential functions
KOKKOS_CUDA_HALF_UNARY_FUNCTION_IMPL(exp, hexp)
KOKKOS_CUDA_HALF_UNARY_FUNCTION_IMPL(exp2, hexp2)
// KOKKOS_CUDA_HALF_UNARY_FUNCTION_IMPL(expm1)
KOKKOS_CUDA_HALF_UNARY_FUNCTION_IMPL(log, hlog)
KOKKOS_CUDA_HALF_UNARY_FUNCTION_IMPL(log10, hlog10)
KOKKOS_CUDA_HALF_UNARY_FUNCTION_IMPL(log2, hlog2)
// KOKKOS_CUDA_HALF_UNARY_FUNCTION_IMPL(log1p)
// Power functions
// KOKKOS_CUDA_HALF_BINARY_FUNCTION_IMPL(pow)
KOKKOS_CUDA_HALF_UNARY_FUNCTION_IMPL(sqrt, hsqrt)
// KOKKOS_CUDA_HALF_UNARY_FUNCTION_IMPL(cbrt)
// KOKKOS_CUDA_HALF_BINARY_FUNCTION_IMPL(hypot)
// Trigonometric functions
KOKKOS_CUDA_HALF_UNARY_FUNCTION_IMPL(sin, hsin)
KOKKOS_CUDA_HALF_UNARY_FUNCTION_IMPL(cos, hcos)
// KOKKOS_CUDA_HALF_UNARY_FUNCTION_IMPL(tan)
// KOKKOS_CUDA_HALF_UNARY_FUNCTION_IMPL(asin)
// KOKKOS_CUDA_HALF_UNARY_FUNCTION_IMPL(acos)
// KOKKOS_CUDA_HALF_UNARY_FUNCTION_IMPL(atan)
// KOKKOS_CUDA_HALF_BINARY_FUNCTION_IMPL(atan2)
// Hyperbolic functions
// KOKKOS_CUDA_HALF_UNARY_FUNCTION_IMPL(sinh)
// KOKKOS_CUDA_HALF_UNARY_FUNCTION_IMPL(cosh)
// KOKKOS_CUDA_HALF_UNARY_FUNCTION_IMPL(tanh)
// KOKKOS_CUDA_HALF_UNARY_FUNCTION_IMPL(asinh)
// KOKKOS_CUDA_HALF_UNARY_FUNCTION_IMPL(acosh)
// KOKKOS_CUDA_HALF_UNARY_FUNCTION_IMPL(atanh)
// Error and gamma functions
// KOKKOS_CUDA_HALF_UNARY_FUNCTION_IMPL(erf)
// KOKKOS_CUDA_HALF_UNARY_FUNCTION_IMPL(erfc)
// KOKKOS_CUDA_HALF_UNARY_FUNCTION_IMPL(tgamma)
// KOKKOS_CUDA_HALF_UNARY_FUNCTION_IMPL(lgamma)
// Nearest integer floating point functions
KOKKOS_CUDA_HALF_UNARY_FUNCTION_IMPL(ceil, hceil)
KOKKOS_CUDA_HALF_UNARY_FUNCTION_IMPL(floor, hfloor)
KOKKOS_CUDA_HALF_UNARY_FUNCTION_IMPL(trunc, htrunc)
// KOKKOS_CUDA_HALF_UNARY_FUNCTION_IMPL(round, hrint)
// KOKKOS_CUDA_HALF_UNARY_FUNCTION_IMPL(nearbyint)
// KOKKOS_CUDA_HALF_UNARY_FUNCTION_IMPL(logb)
// KOKKOS_CUDA_HALF_BINARY_FUNCTION_IMPL(nextafter)
// KOKKOS_CUDA_HALF_BINARY_FUNCTION_IMPL(copysign)
// KOKKOS_CUDA_HALF_UNARY_PREDICATE_IMPL(isfinite)
KOKKOS_CUDA_HALF_UNARY_PREDICATE_IMPL(isinf, __hisinf)
KOKKOS_CUDA_HALF_UNARY_PREDICATE_IMPL(isnan, __hisnan)
// KOKKOS_CUDA_HALF_UNARY_PREDICATE_IMPL(signbit)

#undef KOKKOS_CUDA_HALF_UNARY_FUNCTION_IMPL
#undef KOKKOS_CUDA_HALF_BINARY_FUNCTION_IMPL
#undef KOKKOS_CUDA_HALF_UNARY_PREDICATE_IMPL

#endif
#ifdef KOKKOS_IMPL_BHALF_TYPE_DEFINED

#define KOKKOS_CUDA_BHALF_UNARY_FUNCTION_IMPL(OP, CUDA_NAME) \
  KOKKOS_CUDA_HALF_UNARY_FUNCTION(OP, CUDA_NAME, Kokkos::Experimental::bhalf_t)

#define KOKKOS_CUDA_BHALF_BINARY_FUNCTION_IMPL(OP, CUDA_NAME) \
  KOKKOS_CUDA_HALF_BINARY_FUNCTION(OP, CUDA_NAME, Kokkos::Experimental::bhalf_t)

#define KOKKOS_CUDA_BHALF_UNARY_PREDICATE_IMPL(OP, CUDA_NAME) \
  KOKKOS_CUDA_HALF_UNARY_PREDICATE(OP, CUDA_NAME, Kokkos::Experimental::bhalf_t)

// Basic operations
KOKKOS_CUDA_BHALF_UNARY_FUNCTION_IMPL(abs, __habs)
KOKKOS_CUDA_BHALF_UNARY_FUNCTION_IMPL(fabs, __habs)
// KOKKOS_CUDA_BHALF_BINARY_FUNCTION_IMPL(fmod)
// KOKKOS_CUDA_BHALF_BINARY_FUNCTION_IMPL(remainder)
KOKKOS_CUDA_BHALF_BINARY_FUNCTION_IMPL(fmax, __hmax)
KOKKOS_CUDA_BHALF_BINARY_FUNCTION_IMPL(fmin, __hmin)
// KOKKOS_CUDA_BHALF_BINARY_FUNCTION_IMPL(fdim)
// Exponential functions
KOKKOS_CUDA_BHALF_UNARY_FUNCTION_IMPL(exp, hexp)
KOKKOS_CUDA_BHALF_UNARY_FUNCTION_IMPL(exp2, hexp2)
// KOKKOS_CUDA_BHALF_UNARY_FUNCTION_IMPL(expm1)
KOKKOS_CUDA_BHALF_UNARY_FUNCTION_IMPL(log, hlog)
KOKKOS_CUDA_BHALF_UNARY_FUNCTION_IMPL(log10, hlog10)
KOKKOS_CUDA_BHALF_UNARY_FUNCTION_IMPL(log2, hlog2)
// KOKKOS_CUDA_BHALF_UNARY_FUNCTION_IMPL(log1p)
// Power functions
// KOKKOS_CUDA_BHALF_BINARY_FUNCTION_IMPL(pow)
KOKKOS_CUDA_BHALF_UNARY_FUNCTION_IMPL(sqrt, hsqrt)
// KOKKOS_CUDA_BHALF_UNARY_FUNCTION_IMPL(cbrt)
// KOKKOS_CUDA_BHALF_BINARY_FUNCTION_IMPL(hypot)
// Trigonometric functions
KOKKOS_CUDA_BHALF_UNARY_FUNCTION_IMPL(sin, hsin)
KOKKOS_CUDA_BHALF_UNARY_FUNCTION_IMPL(cos, hcos)
// KOKKOS_CUDA_BHALF_UNARY_FUNCTION_IMPL(tan)
// KOKKOS_CUDA_BHALF_UNARY_FUNCTION_IMPL(asin)
// KOKKOS_CUDA_BHALF_UNARY_FUNCTION_IMPL(acos)
// KOKKOS_CUDA_BHALF_UNARY_FUNCTION_IMPL(atan)
// KOKKOS_CUDA_BHALF_BINARY_FUNCTION_IMPL(atan2)
// Hyperbolic functions
// KOKKOS_CUDA_BHALF_UNARY_FUNCTION_IMPL(sinh)
// KOKKOS_CUDA_BHALF_UNARY_FUNCTION_IMPL(cosh)
// KOKKOS_CUDA_BHALF_UNARY_FUNCTION_IMPL(tanh)
// KOKKOS_CUDA_BHALF_UNARY_FUNCTION_IMPL(asinh)
// KOKKOS_CUDA_BHALF_UNARY_FUNCTION_IMPL(acosh)
// KOKKOS_CUDA_BHALF_UNARY_FUNCTION_IMPL(atanh)
// Error and gamma functions
// KOKKOS_CUDA_BHALF_UNARY_FUNCTION_IMPL(erf)
// KOKKOS_CUDA_BHALF_UNARY_FUNCTION_IMPL(erfc)
// KOKKOS_CUDA_BHALF_UNARY_FUNCTION_IMPL(tgamma)
// KOKKOS_CUDA_BHALF_UNARY_FUNCTION_IMPL(lgamma)
// Nearest integer floating point functions
KOKKOS_CUDA_BHALF_UNARY_FUNCTION_IMPL(ceil, hceil)
KOKKOS_CUDA_BHALF_UNARY_FUNCTION_IMPL(floor, hfloor)
KOKKOS_CUDA_BHALF_UNARY_FUNCTION_IMPL(trunc, hrint)
// KOKKOS_CUDA_BHALF_UNARY_FUNCTION_IMPL(round, hrint)
// KOKKOS_CUDA_BHALF_UNARY_FUNCTION_IMPL(nearbyint)
// KOKKOS_CUDA_BHALF_UNARY_FUNCTION_IMPL(logb)
// KOKKOS_CUDA_BHALF_BINARY_FUNCTION_IMPL(nextafter)
// KOKKOS_CUDA_BHALF_BINARY_FUNCTION_IMPL(copysign)
// KOKKOS_CUDA_BHALF_UNARY_PREDICATE_IMPL(isfinite)
KOKKOS_CUDA_BHALF_UNARY_PREDICATE_IMPL(isinf, __hisinf)
KOKKOS_CUDA_BHALF_UNARY_PREDICATE_IMPL(isnan, __hisnan)
// KOKKOS_CUDA_BHALF_UNARY_PREDICATE_IMPL(signbit)

#undef KOKKOS_CUDA_BHALF_UNARY_FUNCTION_IMPL
#undef KOKKOS_CUDA_BHALF_BINARY_FUNCTION_IMPL
#undef KOKKOS_CUDA_BHALF_UNARY_PREDICATE_IMPL

#endif

#undef KOKKOS_CUDA_HALF_UNARY_FUNCTION
#undef KOKKOS_CUDA_HALF_BINARY_FUNCTION
#undef KOKKOS_CUDA_HALF_UNARY_PREDICATE

#endif
}  // namespace Kokkos

#endif
