sudo: false

language: cpp

os:
  - linux
  - osx

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - clang

compiler:
  - gcc
  - clang

env:
  - THREADING="serial"
  - THREADING="openmp"
  - THREADING="pthread"

# Apple GCC does not support OpenMP.  GCC with OpenMP requires Homebrew.
# Apple Clang does not support OpenMP.  Clang with OpenMP requires Homebrew.
# Clang OpenMP support is not always available.
matrix:
  exclude:
    - compiler: clang
      env: THREADING="openmp"
    - os: osx
      env: THREADING="openmp"
    - os: osx
      compiler: gcc

script:
  - export OMP_NUM_THREADS=2
  - export OMP_PLACES=threads
  - export OMP_PROC_BIND=threads
  - mkdir build
  - cd build
  - ../generate_makefile.bash --compiler=$CXX --with-$THREADING --with-options=compiler_warnings
  - make
  - make test
