# SPDX-FileCopyrightText: Copyright 2026 Antmicro
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

load("@bazel_skylib//rules:common_settings.bzl", "string_flag")
load("@bazel_skylib//rules:write_file.bzl", "write_file")
load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("//bazel:options.bzl", "CXX_COPTS", "LINKOPTS", "OPENMP_DEPS", "SUPPORTED_PLATFORMS")

package(default_visibility = ["//visibility:public"])

string_flag(
    name = "backend",
    build_setting_default = "serial",
    values = [
        "openmp",
        "serial",
        "threads",
    ],
)

config_setting(
    name = "openmp",
    flag_values = {":backend": "openmp"},
)

config_setting(
    name = "threads",
    flag_values = {":backend": "threads"},
)

genrule(
    name = "config",
    srcs = [
        "//bazel:generate_config.cmake",
        "cmake/kokkos_version.cmake",
        "cmake/KokkosCore_config.h.in",
        "tpls/desul-hash.txt",
        "tpls/mdspan-hash.txt",
    ],
    outs = ["include/KokkosCore_config.h"],
    cmd = "cmake -DLIBDL=ON -DOUTPUT=\"$@\" -DBACKEND=" + select({
        ":openmp": "openmp",
        ":threads": "threads",
        "//conditions:default": "serial",
    }) + " -P $(location //bazel:generate_config.cmake)",
)

write_file(
    name = "declare_backend",
    out = "include/KokkosCore_Config_DeclareBackend.hpp",
    content = ["#include <decl/Kokkos_Declare_SERIAL.hpp>"] + select({
        ":openmp": ["#include <decl/Kokkos_Declare_OPENMP.hpp>"],
        ":threads": ["#include <decl/Kokkos_Declare_THREADS.hpp>"],
        "//conditions:default": [],
    }),
)

write_file(
    name = "fwd_backend",
    out = "include/KokkosCore_Config_FwdBackend.hpp",
    content = ["#include <fwd/Kokkos_Fwd_SERIAL.hpp>"] + select({
        ":openmp": ["#include <fwd/Kokkos_Fwd_OPENMP.hpp>"],
        ":threads": ["#include <fwd/Kokkos_Fwd_THREADS.hpp>"],
        "//conditions:default": [],
    }),
)

write_file(
    name = "setup_backend",
    out = "include/KokkosCore_Config_SetupBackend.hpp",
    content = [""],
)

write_file(
    name = "desul_config",
    out = "include/desul/atomics/Config.hpp",
    content = ["#pragma once"],
)

cc_library(
    name = "kokkos",
    srcs = glob([
        "core/src/impl/*.cpp",
        "core/src/Serial/*.cpp",
        "containers/src/impl/*.cpp",
    ]) + select({
        ":openmp": glob(["core/src/OpenMP/*.cpp"]),
        ":threads": glob(["core/src/Threads/*.cpp"]),
        "//conditions:default": [],
    }),
    hdrs = glob([
        "core/src/**/*.hpp",
        "core/src/**/*.h",
        "containers/src/**/*.hpp",
        "algorithms/src/**/*.hpp",
        "tpls/desul/include/**",
        "tpls/mdspan/include/**",
    ]) + [
        ":config",
        ":declare_backend",
        ":desul_config",
        ":fwd_backend",
        ":setup_backend",
    ],
    copts = CXX_COPTS,
    includes = [
        "algorithms/src",
        "containers/src",
        "core/src",
        "include",
        "tpls/desul/include",
        "tpls/mdspan/include",
    ],
    linkopts = LINKOPTS,
    target_compatible_with = SUPPORTED_PLATFORMS,
    deps = OPENMP_DEPS,
)
