ARG BASE=rocm/dev-ubuntu-20.04:5.2-complete@sha256:4030c8af0c06c286174758523dabe4b3850bf72d4a8c1ef275d3ec69aa475f65
FROM $BASE

RUN apt-get update && apt-get install -y \
        kmod \
        wget \
        ccache \
        cmake \
        file \
        && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENV PATH=/opt/rocm/bin:$PATH
