FROM ubuntu:24.04

RUN apt-get update && apt-get install -y \
        bc \
        git \
        build-essential \
        clang-format-16 \
        wget \
        && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENV CLANG_FORMAT_EXE=clang-format-16
