FROM ubuntu:24.04@sha256:2e863c44b718727c860746568e1d54afd13b2fa71b160f5cd9058fc436217b30

ARG ADDITIONAL_PACKAGES

RUN apt-get update && apt-get install -y \
        bc \
        git \
        build-essential \
        clang-format-16 \
        wget \
        ${ADDITIONAL_PACKAGES} \
        && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENV CLANG_FORMAT_EXE=clang-format-16
