spack:
  specs:
    # Kokkos 5 requires CMake >= 3.22
    - cmake@3.22 arch=linux-rhel9-x86_64
    - "openblas@0.3.29 arch=linux-rhel9-x86_64"
    - "cuda@12.2.2 arch=linux-rhel9-x86_64"

  concretizer:
    targets:
      host_compatible: false
    unify: true

  # cause all of the includes to go into one place
  view:
    default:
      root: /cuda
