include:
  - project: 'anl/ci-resources/defaults'
    ref: main
    file:
      - '/runners.yml'

Polaris:
  stage: test
  extends: .polaris-shell-runner
  script:
    - module use /opt/cray/pe/lmod/modulefiles/core
    - module use /opt/cray/pe/lmod/modulefiles/craype-targets/default
    - module load craype-x86-milan craype-accel-nvidia80
    - module swap PrgEnv-nvhpc PrgEnv-gnu
    - module use /soft/modulefiles
    - module load cuda-PrgEnv-nvidia/12.2.91
    - module load spack-pe-base/0.8.1
    - module load cmake/3.27.9 gcc/11.4.0
    - module list
    - git clone https://github.com/kokkos/kokkos.git
    - cd kokkos
    - export CMAKE_BUILD_PARALLEL_LEVEL=48
    - export ENV_CMAKE_OPTIONS=""
    - export ENV_CMAKE_OPTIONS="${ENV_CMAKE_OPTIONS};-D CMAKE_CXX_COMPILER=`pwd`/bin/nvcc_wrapper"
    - export ENV_CMAKE_OPTIONS="${ENV_CMAKE_OPTIONS};-D CMAKE_VERBOSE_MAKEFILE=ON"
    - export ENV_CMAKE_OPTIONS="${ENV_CMAKE_OPTIONS};-D CMAKE_CXX_FLAGS='-Werror=all-warnings -Werror'"
    - export ENV_CMAKE_OPTIONS="${ENV_CMAKE_OPTIONS};-D Kokkos_ARCH_AMPERE80=ON"
    - export ENV_CMAKE_OPTIONS="${ENV_CMAKE_OPTIONS};-D Kokkos_ENABLE_CUDA=ON;"
    - export ENV_CMAKE_OPTIONS="${ENV_CMAKE_OPTIONS};-D Kokkos_ENABLE_COMPILER_WARNINGS=ON;"
    - export ENV_CMAKE_OPTIONS="${ENV_CMAKE_OPTIONS};-D Kokkos_ENABLE_TESTS=ON"
    - ctest -VV
        -D CDASH_MODEL=Nightly
        -D CMAKE_OPTIONS="${ENV_CMAKE_OPTIONS}"
        -S CTestRun.cmake
        -D CTEST_SITE="gitlab-ci.alcf.anl.gov"
        -D CTEST_BUILD_NAME="Polaris-A100"
