INTEL-DATA-CENTER-MAX-1100:
  stage: test
  tags: [intel-data-center-max-1100]
  image: intel/oneapi-basekit:2023.1.0-devel-ubuntu22.04
  script:
    - sycl-ls
    - export ONEAPI_DEVICE_SELECTOR=level_zero:gpu
    - cmake
      -B build
      -DCMAKE_BUILD_TYPE=Release
      -DCMAKE_CXX_COMPILER=icpx
      -DKokkos_ENABLE_SYCL=ON
      -DKokkos_ARCH_INTEL_PVC=ON
      -DKokkos_ENABLE_TESTS=ON
      -DCMAKE_CXX_FLAGS='-fsycl-device-code-split=per_kernel -fp-model=precise'
    - cd build
    - make -j48 Kokkos_CoreUnitTest_SYCL1A && ./core/unit_test/Kokkos_CoreUnitTest_SYCL1A 
  artifacts:
    when: always
    paths:
      - build/result_pvc1100.xml
    reports:
      junit: build/result_pvc1100.xml
