NVIDIA-GH200:
  stage: test
  tags: [nvidia-gh200]
  image: masterleinad/kokkos-nvcc:12.6.1
  script:
    - cmake
      -B build
      -DCMAKE_CXX_COMPILER=`pwd`/bin/nvcc_wrapper
      -DCMAKE_CXX_FLAGS="-Werror=all-warnings -Werror"
      -DKokkos_ARCH_HOPPER90=ON
      -DKokkos_ENABLE_CUDA=ON
      -DKokkos_ENABLE_COMPILER_WARNINGS=ON
      -DKokkos_ENABLE_IMPL_CUDA_UNIFIED_MEMORY=ON
      -DKokkos_ENABLE_TESTS=ON
    - cmake --build build -j48
    - cd build
    - ctest -V --output-junit result_gh200.xml
  artifacts:
    when: always
    paths:
      - build/result_gh200.xml
    reports:
      junit: build/result_gh200.xml

INTEL-DATA-CENTER-MAX-1100:
  stage: test
  tags: [intel-data-center-max-1100]
  image: intel/oneapi-basekit:2024.2.1-0-devel-ubuntu22.04
  script:
    - sycl-ls
    - export ONEAPI_DEVICE_SELECTOR=level_zero:gpu
    - cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=icpx -DKokkos_ENABLE_SYCL=ON -DKokkos_ARCH_INTEL_PVC=ON -DKokkos_ENABLE_TESTS=ON -DCMAKE_CXX_FLAGS="-fsycl-device-code-split=per_kernel -fp-model=precise"
    - cmake --build build -j48
    - cd build
    - ctest -V --output-junit result_pvc1100.xml
  artifacts:
    when: always
    paths:
      - build/result_pvc1100.xml
    reports:
      junit: build/result_pvc1100.xml

AMD-MI300A:
  stage: test
  tags: [uo-gpu, odyssey, amd-mi300]
  image: rocm/dev-ubuntu-24.04:6.2.4-complete
  script:
    - sudo apt-get update && sudo apt-get install -y cmake
    - export GTEST_FILTER=-hip.unified_memory_zero_memset
    - cmake
      -B build
      -DCMAKE_BUILD_TYPE=Release
      -DCMAKE_CXX_COMPILER=hipcc
      -DKokkos_ENABLE_HIP=ON
      -DKokkos_ARCH_AMD_GFX942_APU=ON
      -DKokkos_ARCH_NATIVE=ON
      -Drocthrust_ROOT=/opt/rocm-6.2.4
      -DKokkos_ENABLE_TESTS=ON
      -DCMAKE_CXX_FLAGS='-Werror'
      -DKokkos_ENABLE_COMPILER_WARNINGS=ON
    - cmake --build build -j48 --verbose
    - cd build
    - ctest -V --output-junit result_mi300a.xml
  artifacts:
    when: always
    paths:
      - build/result_mi300a.xml
    reports:
      junit: build/result_mi300a.xml
