test:
  stage: test
  tags: [nvidia-gh200]
  image: masterleinad/kokkos-nvcc:12.6.1
  script:
    - cmake -B build -DKokkos_ENABLE_CUDA=ON -DKokkos_ARCH_HOPPER90=ON -DKokkos_ENABLE_IMPL_CUDA_UNIFIED_MEMORY=ON -DKokkos_ENABLE_TESTS=ON
    - cmake --build build -j48
    - cd build
    - ctest -V
