#! /usr/bin/env bash

# $1 is the name of the environment file to source
# $2 is the path to the Trilinos repo
# $3 is the path to the Kokkos repo
# $4 is the path to the Kokkos Kernels repo

export ENV_FILE=$1
export TRILINOS_PATH=$2
export KOKKOS_PATH=$3
export KOKKOSKERNELS_PATH=$4

if [ -z ${ENV_FILE} ] || [ ! -f ${ENV_FILE} ]; then
  >&2 echo "Must give valid environment file as first argument"
fi

if [ -z ${TRILINOS_PATH} ] || [ ! -d ${TRILINOS_PATH} ]; then
  >&2 echo "Must give valid Trilinos path  as second argument"
fi

if [ -z ${KOKKOS_PATH} ] || [ ! -d ${KOKKOS_PATH} ]; then
  >&2 echo "Must give valid Kokkos path  as third argument"
fi

if [ -z ${KOKKOSKERNELS_PATH} ] || [ ! -d ${KOKKOSKERNELS_PATH} ]; then
  >&2 echo "Must give valid KokkosKernels path  as fourth argument"
fi

source ${ENV_FILE}

ln -s ${KOKKOS_PATH} ${TRILINOS_PATH}/kokkos
ln -s ${KOKKOSKERNELS_PATH} ${TRILINOS_PATH}/kokkos-kernels

if [ ! -d "${KOKKOS_PATH}" ]; then
  mkdir promotion-test
else
  rm -rf promotion-test
  mkdir promotion-test
fi

cd promotion-test

${TRILINOS_PATH}/sampleScripts/Sandia-SEMS/configure-testbeds-jenkins-all \
  -DKokkos_OVERRIDE_SOURCE_DIR=kokkos \
  -DKokkosKernels_OVERRIDE_SOURCE_DIR=kokkos-kernels

make -j 
make test


