#!/bin/bash -el
ulimit -c 0

module load devpack/openmpi/1.10.4/gcc/5.4.0/cuda/8.0.44
export OMP_NUM_THREADS=8
export JENKINS_DO_CUDA=OFF
export JENKINS_DO_OPENMP=ON
export JENKINS_DO_PTHREAD=OFF
export JENKINS_DO_SERIAL=OFF
export JENKINS_DO_COMPLEX=OFF

export JENKINS_ARCH_CXX_FLAG="-mcpu=power8"
export JENKINS_ARCH_C_FLAG="-mcpu=power8"
export BLAS_LIBRARIES="${BLAS_ROOT}/lib/libblas.a;gfortran;gomp"
export LAPACK_LIBRARIES="${LAPACK_ROOT}/lib/liblapack.a;gfortran;gomp"

export JENKINS_DO_TESTS=ON
export JENKINS_DO_EXAMPLES=ON

export QUEUE=rhel7F

module load python

export KOKKOS_PATH=${PWD}/kokkos

#Already done:
if [ ! -d "${KOKKOS_PATH}" ]; then
  git clone https://github.com/kokkos/kokkos ${KOKKOS_PATH}
fi

cd ${KOKKOS_PATH}
git checkout develop
git pull
cd ..

source ${KOKKOS_PATH}/config/trilinos-integration/prepare_trilinos_repos.sh

${TRILINOS_UPDATED_PATH}/sampleScripts/Sandia-SEMS/run_repo_comparison_lsf ${TRILINOS_UPDATED_PATH} ${TRILINOS_PRISTINE_PATH} ${TRILINOS_UPDATED_PATH}/sampleScripts/Sandia-SEMS/configure-testbeds-jenkins-all TestCompare ${QUEUE}

