// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
// SPDX-FileCopyrightText: Copyright Contributors to the Kokkos project

#ifndef KOKKOS_TEST_EVENT_HELPERS_HPP
#define KOKKOS_TEST_EVENT_HELPERS_HPP

#include <Kokkos_Core.hpp>

// Functors shared between the portable Event tests (TestEvent.hpp) and the
// CUDA-specific Event tests (cuda/TestCuda_CudaEvent.cpp).
// NVCC cannot handle extended __host__ __device__ lambdas inside the private
// TestBody() generated by the TEST() macro, so named functors are required.

namespace Test {

template <class ViewType>
struct FillFunctor {
  ViewType data;
  KOKKOS_FUNCTION void operator()(int i) const { data(i) = i + 1; }
};

template <class ViewType>
struct ProduceFunctor {
  ViewType data;
  KOKKOS_FUNCTION void operator()(int i) const { data(i) = i * 2; }
};

template <class ViewType, class ResultType>
struct ConsumeFunctor {
  ViewType data;
  ResultType result;
  KOKKOS_FUNCTION void operator()(int i) const {
    Kokkos::atomic_add(&result(), static_cast<int64_t>(data(i)));
  }
};

}  // namespace Test

#endif  // KOKKOS_TEST_EVENT_HELPERS_HPP
