INCLUDE(CheckIncludeFileCXX)
CHECK_INCLUDE_FILE_CXX(oneapi/dpl/execution KOKKOS_COMPILER_HAS_ONEDPL_EXECUTION_HEADER)
CHECK_INCLUDE_FILE_CXX(oneapi/dpl/algorithm KOKKOS_COMPILER_HAS_ONEDPL_ALGORITHM_HEADER)

IF (KOKKOS_COMPILER_HAS_ONEDPL_EXECUTION_HEADER AND KOKKOS_COMPILER_HAS_ONEDPL_ALGORITHM_HEADER)
  KOKKOS_CREATE_IMPORTED_TPL(ONEDPL INTERFACE)
ELSE()
  FIND_PACKAGE(oneDPL REQUIRED)
  KOKKOS_CREATE_IMPORTED_TPL(
    ONEDPL INTERFACE
    LINK_LIBRARIES oneDPL
    # FIXME_SYCL is there a better way of fixing the problem with compatibility of oneTBB vs legacy TBB?
    # https://stackoverflow.com/questions/67923287/how-to-resolve-no-member-named-task-in-namespace-tbb-error-when-using-oned/
    COMPILE_DEFINITIONS PSTL_USE_PARALLEL_POLICIES=0 _GLIBCXX_USE_TBB_PAR_BACKEND=0
  )
ENDIF()
