#
# To get workflow IDs, visit:
#   https://api.github.com/repos/kokkos/kokkos/actions/workflows
#
name: cancel-previous-workflows

on: [push, pull_request]

jobs:
  cancel:
    name: 'Cancel Previous Workflows'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.6.0
        with:
          workflow_id: 3979336,3979050
          access_token: ${{ github.token }}
