name: clang-format check

on:
  workflow_call:

permissions: read-all

jobs:
  clang-formatting-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
    - name: Run clang-format style check.
      uses: DoozyX/clang-format-lint-action@bcb4eb2cb0d707ee4f3e5cc3b456eb075f12cf73 # v0.20
      with:
        clangFormatVersion: 16
