name: cmake-format check

on:
  workflow_call:

permissions: read-all

jobs:
  cmake-formatting-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    - name: cmake-format lint action
      uses: puneetmatharu/cmake-format-lint-action@2ac346e79e7ceac958bc637c1391285fb335ed7c # v1.0.5
      with:
        args: --config-files .cmake-format.py --in-place
        file-regex: '(.*\.cmake$|.*\.cmake\.in$|CMakeLists.txt$)'
    - name: check
      run: git diff --exit-code
