name: Weekly CEA builds

on:
  schedule:
    - cron: "0 2 * * 6" # every Saturday at 2am UTC
  workflow_dispatch:

jobs:
  build_and_test:
    env:
      build_jobs: 20

    strategy:
      matrix:
        build_type:
          - Release
          - Debug
        backend:
          - name: cuda-a100
            flags: -DKokkos_ENABLE_CUDA=ON -DKokkos_ARCH_AMPERE80=ON
            modules: gcc/11.2.0/gcc-4.8.5 cuda/12.2.1/gcc-11.2.0 cmake/3.28.3/gcc-11.2.0
            slurm_args: --nodes=1 --time=01:00:00 --mem=80G -p gpua100 --gres=gpu:1
            runner: [self-hosted, cuda]

    runs-on: ${{ matrix.backend.runner }}

    steps:
      - uses: actions/checkout@v4

      - name: Configure
        run: |
          module load ${{ matrix.backend.modules }}
          cmake -B build \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -DCMAKE_CXX_STANDARD=17 \
            -DCMAKE_CXX_FLAGS=-Werror \
            -DKokkos_ENABLE_COMPILER_WARNINGS=ON \
            -DKokkos_ENABLE_TESTS=ON \
            -DKokkos_ENABLE_EXAMPLES=ON \
            ${{ matrix.backend.flags }}

      - name: Build
        run: |
          module load ${{ matrix.backend.modules }}
          cmake --build build --parallel $build_jobs

      - name: Test
        run: |
          module load ${{ matrix.backend.modules }}
          srun ${{ matrix.backend.slurm_args }} \
          ctest --test-dir build --output-on-failure
